trigger: none

pool:
      vmImage: ubuntu-latest
      
variables:
  imageRepo: sampleapp
  tag: '$(Build.BuildId)'
  serviceconnection: K8s-Azure-container-registry

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: $(serviceconnection)
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: '$(tag)'
   
